"""
Batch runner for the MT adequacy spot-check: calls the real, already-running
POST /v1/pivot service (services/ai/mt/app.py) for every FLORES-200 sample
and, if present, every real community sample, and saves the results for
rate_adequacy.py to grade.

Usage:
    cd services/ai
    ./.venv/Scripts/python.exe -m uvicorn mt.app:app --port 8004   # separate terminal
    PYTHONPATH=../.. ./.venv/Scripts/python.exe mt/bakeoff/run_batch.py

Does not judge translation quality itself -- that's rate_adequacy.py, and
that's a human call.
"""

from __future__ import annotations

import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[4]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from services.ai.mt.settings import Settings  # noqa: E402

_BAKEOFF_DIR = Path(__file__).resolve().parent
_FLORES_PATH = _BAKEOFF_DIR / "flores_samples.json"
_COMMUNITY_PATH = _BAKEOFF_DIR / "community_samples.txt"
_RESULTS_PATH = _BAKEOFF_DIR / "results.json"


def load_flores_entries() -> list[dict]:
    payload = json.loads(_FLORES_PATH.read_text(encoding="utf-8"))
    entries = []
    for sample in payload["samples"]:
        entries.append(
            {
                "id": f"flores:{sample['language_pair']}:{sample['line_index']}",
                "source_type": "flores",
                "source_language": sample["source_language"],
                "source_text": sample["source_text"],
                "reference_text": sample["reference_text"],
            }
        )
    return entries


def load_community_entries() -> list[dict]:
    """Parses `[te] ...` / `[hi] ...` lines. Missing file is expected and
    fine -- the community sample file is real, human-provided content that's
    filled in manually, not generated by this tooling."""
    if not _COMMUNITY_PATH.is_file():
        return []

    entries = []
    for i, raw_line in enumerate(_COMMUNITY_PATH.read_text(encoding="utf-8").splitlines()):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if not (line.startswith("[te]") or line.startswith("[hi]")):
            print(f"WARNING: community_samples.txt line {i + 1} has no [te]/[hi] tag, skipping: {line!r}")
            continue
        lang = line[1:3]
        text = line[4:].strip()
        if not text:
            continue
        entries.append(
            {
                "id": f"community:{lang}:{i + 1}",
                "source_type": "community",
                "source_language": lang,
                "source_text": text,
                "reference_text": None,
            }
        )
    return entries


def call_pivot(base_url: str, text: str, source_language: str) -> tuple[dict, float]:
    body = json.dumps({"text": text, "source_language": source_language}).encode("utf-8")
    req = urllib.request.Request(
        f"{base_url}/v1/pivot",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    start = time.perf_counter()
    with urllib.request.urlopen(req, timeout=60) as resp:
        response_body = json.loads(resp.read().decode("utf-8"))
    latency_ms = (time.perf_counter() - start) * 1000
    return response_body, latency_ms


def main() -> None:
    settings = Settings.from_env()
    base_url = f"http://127.0.0.1:{settings.port}"

    entries = load_flores_entries() + load_community_entries()
    if not entries:
        print("No entries found (flores_samples.json is missing?) -- nothing to do.")
        return

    n_community = sum(1 for e in entries if e["source_type"] == "community")
    print(
        f"Loaded {len(entries)} entries "
        f"({len(entries) - n_community} FLORES, {n_community} community). "
        f"Calling {base_url}/v1/pivot ..."
    )

    results = []
    for i, entry in enumerate(entries, start=1):
        print(f"Translating {i}/{len(entries)}...")
        try:
            response_body, latency_ms = call_pivot(
                base_url, entry["source_text"], entry["source_language"]
            )
        except urllib.error.URLError as exc:
            print(
                f"ERROR calling /v1/pivot for {entry['id']}: {exc}. "
                "Is the MT service running (see docstring for the uvicorn command)?"
            )
            raise SystemExit(1) from exc

        results.append(
            {
                "id": entry["id"],
                "source_type": entry["source_type"],
                "source_language": entry["source_language"],
                "source_text": entry["source_text"],
                "reference_text": entry["reference_text"],
                "translation": response_body.get("pivot_text"),
                "model_version": response_body.get("model_version"),
                "latency_ms": round(latency_ms, 2),
            }
        )

    _RESULTS_PATH.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(results)} results to {_RESULTS_PATH}")


if __name__ == "__main__":
    main()
