"""initial schema: users, circles, memberships, conversations, messages

Revision ID: 8761697bd6bb
Revises:
Create Date: 2026-08-18 18:35:46.847558

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8761697bd6bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("photo", sa.Text(), nullable=True),
        sa.Column("preferred_language", sa.Text(), nullable=False),
        sa.Column("tts_on", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'elder'"), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('elder', 'moderator', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "circles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_a", sa.UUID(), nullable=False),
        sa.Column("user_b", sa.UUID(), nullable=False),
        sa.CheckConstraint("user_a < user_b", name="ck_conversations_canonical_order"),
        sa.ForeignKeyConstraint(["user_a"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_b"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a", "user_b", name="uq_conversations_user_pair"),
    )
    op.create_table(
        "memberships",
        sa.Column("circle_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'member'"), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("role IN ('member', 'moderator', 'admin')", name="ck_memberships_role"),
        sa.ForeignKeyConstraint(["circle_id"], ["circles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("circle_id", "user_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_msg_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("target_circle_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("pivot_text_en", sa.Text(), nullable=True),
        sa.Column("original_media_ref", sa.Text(), nullable=True),
        sa.Column("media_duration_ms", sa.Integer(), nullable=True),
        sa.Column("source_lang", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("undo_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'text' AND text IS NOT NULL) OR (kind = 'voice' AND original_media_ref IS NOT NULL)",
            name="ck_messages_kind_payload",
        ),
        sa.CheckConstraint("kind IN ('text', 'voice')", name="ck_messages_kind"),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'held', 'blocked', 'failed')",
            name="ck_messages_status",
        ),
        sa.CheckConstraint(
            "target_type <> 'circle' OR conversation_id = target_circle_id",
            name="ck_messages_conversation_id_matches_circle",
        ),
        sa.CheckConstraint("target_type IN ('user', 'circle')", name="ck_messages_target_type"),
        sa.CheckConstraint(
            "num_nonnulls(target_user_id, target_circle_id) = 1",
            name="ck_messages_target_exactly_one",
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_circle_id"], ["circles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("author_id", "client_msg_id", name="uq_messages_author_client_msg_id"),
    )
    op.create_index(
        "ix_messages_conversation_id_id_not_deleted",
        "messages",
        ["conversation_id", "id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_messages_conversation_id_id_not_deleted",
        table_name="messages",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("messages")
    op.drop_table("memberships")
    op.drop_table("conversations")
    op.drop_table("circles")
    op.drop_table("users")
    # ### end Alembic commands ###
